# 数据库配置
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
    url: jdbc:mysql:///parentboot?useSSL=false
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 连接池最大连接数，默认是10
      maximum-pool-size: 15
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 60000
  # jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  #aop 代理配置
  aop:
    proxy-target-class: true
    auto: true
# MyBatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.chachae.common.core.entity
  mapper-locations: classpath:mappers/*Mapper.xml
# 服务期配置
server:
  servlet:
    context-path: '/api'
  port: 8099