# 数据库配置
spring:
  datasource:
    # 如果存在多个数据源，监控的时候可以通过名字来区分开来
    name: mysql
    # 连接数据库的url
    url: jdbc:mysql://localhost:3306/parentboot?characterEncoding=utf-8&useSSL=false
    # 连接数据库的账号
    username: root
    # 连接数据库的密码
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 扩展插件
    druid:
      max-open-prepared-statements: -1
      pool-prepared-statements: false
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      validation-query: select count(1) from 'table'
      min-evictable-idle-time-millis: 200000
      time-between-eviction-runs-millis: 60000
      min-idle: 1
      max-wait: 60000
      initial-size: 1
      max-active: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        login-username: chachae
        login-password: chachae
        enabled: true
      use-global-data-source-stat: true
  # jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  #aop 代理配置
  aop:
    proxy-target-class: true
    auto: true
# MyBatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.chachae.common.core.entity
  mapper-locations: classpath:mappers/*Mapper.xml
# 服务期配置
server:
  servlet:
    context-path: '/api'
  port: 8099
logging:
  level:
    com: debug